import {
  DashboardOutlined,
  ShoppingCartOutlined,
  SettingOutlined,
  ShoppingOutlined,
  UserOutlined,
  PictureOutlined,
  GiftOutlined,
  ShopOutlined,
  UsergroupAddOutlined,
  MailOutlined,
  MobileOutlined,
  FileTextOutlined,
} from "@ant-design/icons"
import { APP_PREFIX_PATH } from "configs/AppConfig"

const dashBoardNavTree = [
  {
    key: "basic",
    path: `${APP_PREFIX_PATH}/basic`,
    title: "sidenav.basic",
    icon: DashboardOutlined,
    breadcrumb: false,
    submenu: [
      {
        key: "basic-dashboard",
        path: `${APP_PREFIX_PATH}/basic/dashboard`,
        title: "sidenav.basic.dashboard",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-catalog",
        path: `${APP_PREFIX_PATH}/basic/catalog`,
        title: "sidenav.basic.catalog",
        icon: ShoppingCartOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "basic-catalog-products",
            path: `${APP_PREFIX_PATH}/basic/catalog/products`,
            title: "sidenav.basic.catalog.products",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "basic-catalog-categories",
            path: `${APP_PREFIX_PATH}/basic/catalog/categories`,
            title: "sidenav.basic.catalog.categories",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "basic-catalog-collections",
            path: `${APP_PREFIX_PATH}/basic/catalog/collections`,
            title: "sidenav.basic.catalog.collections",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "basic-catalog-combo",
            path: `${APP_PREFIX_PATH}/basic/catalog/combo`,
            title: "sidenav.basic.catalog.combo",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "basic-orders",
        path: `${APP_PREFIX_PATH}/basic/orders`,
        title: "sidenav.basic.orders",
        icon: ShoppingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-clients",
        path: `${APP_PREFIX_PATH}/basic/clients`,
        title: "sidenav.basic.clients",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "basic-clients-clientList",
            path: `${APP_PREFIX_PATH}/basic/clients/client-list`,
            title: "sidenav.basic.clients.clientList",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "basic-clients-clientGroups",
            path: `${APP_PREFIX_PATH}/basic/catalog/client-groups`,
            title: "sidenav.basic.clients.clientGroups",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "basic-banners",
        path: `${APP_PREFIX_PATH}/basic/banners`,
        title: "sidenav.basic.banners",
        icon: PictureOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-promocodes",
        path: `${APP_PREFIX_PATH}/basic/promocodes`,
        title: "sidenav.basic.promocodes",
        icon: GiftOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-shops",
        path: `${APP_PREFIX_PATH}/basic/shops`,
        title: "sidenav.basic.shops",
        icon: ShopOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "basic-shops-addresses",
            path: `${APP_PREFIX_PATH}/basic/catalog/addresses`,
            title: "sidenav.basic.shops.addresses",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "basic-clients-geofences",
            path: `${APP_PREFIX_PATH}/basic/catalog/geofences`,
            title: "sidenav.basic.shops.geofences",
            icon: "",
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "basic-staff",
        path: `${APP_PREFIX_PATH}/basic/staff`,
        title: "sidenav.basic.staff",
        icon: UsergroupAddOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-mailing",
        path: `${APP_PREFIX_PATH}/basic/mailing`,
        title: "sidenav.basic.mailing",
        icon: MailOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
  {
    key: "system",
    path: `${APP_PREFIX_PATH}/system`,
    title: "sidenav.system",
    icon: SettingOutlined,
    breadcrumb: false,
    submenu: [
      {
        key: "system-settings",
        path: `${APP_PREFIX_PATH}/system/settings`,
        title: "sidenav.system.settings",
        icon: SettingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "system-mobileApp",
        path: `${APP_PREFIX_PATH}/system/mobile-app`,
        title: "sidenav.system.mobileApp",
        icon: MobileOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "system-logs",
        path: `${APP_PREFIX_PATH}/system/logs`,
        title: "sidenav.system.logs",
        icon: FileTextOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
]

const navigationConfig = [...dashBoardNavTree]

export default navigationConfig
