export const SET_LOADING = "SET_LOADING"

export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED"
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED"
export const USER_FETCH_FAILURED = "USER_FETCH_FAILURED"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"
export const DELETE_USER = "DELETE_USER"
